### ISSUE TITLE
too transparent on windows 

### ISSUE THREAD

**Issue by samueljim** [evansims/hyper-firewatch#3]
![image](https://user-images.githubusercontent.com/19277887/41896277-7d35f1cc-7967-11e8-99ea-cdad5e031d5a.png)

**Comment by boy51** [comment]
I agree lol

**Comment by evansims** [comment]
Sorry, I don't have any control over how Hyper decides to render on a certain individual OS, it's not defined by the style but the software. You'll need to file a report with Hyper.
